import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import {getSession, useSession, signOut } from "next-auth/react"
import SideNav from '../components/SideNav'

export default function Home({session}) {
  const { data: sessionData } = useSession()
  if(!sessionData){
    return <Login/>;
  }
  else{
    // console.log(sessionData)
    
    return (
      <div className="container pl-10 pr-3">
        <Head>
          <title>Che Media</title>
          <meta name="description" content="Generated by create next app" />
          
        </Head> 
        {/* Header */}
        <Header/> 
        <main className='flex'>

          <SideNav/>
          <h1 className="text-3xl font-bold underline">
          hey
          </h1>
          <button className='btn bg-blue-600 text-white roundend-full' onClick={() => signOut()}>Sign out</button>
        </main>
        
      </div>
    )
  }
  
}

export async function getServerSideProps(context){
  //get the user
  const session = await getSession(context);
  return{
    props:{
      session
    }
  }
}
