import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Login from '../components/Login'
import {getSession, useSession, signIn, signOut } from "next-auth/react"

export default function Home({session}) {
  const { data: sessionData } = useSession()
  if(!sessionData){
    return <Login/>;
  }
  else{
    console.log(sessionData)
    return (
      <div className="">
        <Head>
          <title>Che Media</title>
          <meta name="description" content="Generated by create next app" />
          
        </Head>
        {/* Header */}
        <Header/> 
        <h1 className="text-3xl font-bold underline">
        Hello world!, {sessionData.user.name}
      </h1>
      <button className='btn bg-blue-600 text-white roundend-full' onClick={() => signOut()}>Sign out</button>
      </div>
    )
  }
  
}

export async function getServerSideProps(context){
  //get the user
  const session = await getSession(context);
  return{
    props:{
      session
    }
  }
}
